WRITE_MODE = 'w'
READ_MODE = 'r'
READ_WRITE_MODE = 'r+'

FILE_BEGIN = 0

TREE_MAP_FILE_NAME = 'tree.map'
FILE_MAP_FILE_NAME = 'file.map'

STASH_FOLDER_NAME = 'stash'

LOG_FILE_NAME = 'oram.log'

JSON_INDENT = 4
